In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('processed_data.csv')

In [42]:
cat = ['Bags and Travel','Watches Sunglasses Jewellery']
allprod = []
indup = {}
for i in cat:
    temp = df[df['Category'] == i]
    for j in range(len(temp)):
        sub_sub_category = temp.iloc[j]['Sub-Sub-Category']
        rate_of_change = temp.iloc[j]['Label']
        if sub_sub_category not in indup:
            indup[sub_sub_category] = rate_of_change
        else:
            indup[sub_sub_category] = max(indup[sub_sub_category], rate_of_change)

allprod = [{k: v} for k, v in indup.items()]
sorted_data = sorted(allprod, key=lambda item: list(item.values())[0], reverse=True)

In [43]:
max(df['Rate of Change'])

133.5

In [45]:
sorted_data

[{'Wallets & Accessories': 36.27959859483752},
 {'Clutches': 33.466268059578454},
 {'Top-Handle Bags': 32.88975390460014},
 {'Men': 19.508704082453168},
 {'Travel Accessories': 18.951395175494437},
 {'Cross Body & Shoulder Bags': 18.940892676709723},
 {'Crossbody Bags': 13.672451812875522},
 {'Backpacks': 10.586870301701458},
 {'Laptop Bags': 10.36728148834827},
 {'Women': 5.3319017120465055},
 {'Kids': 4.515146558033226},
 {'Eyeglasses': 4.333122307192999},
 {'Luggage': 3.6466927467646},
 {'Travel Bags': 3.326407644062229},
 {'Tote Bags': 2.1910409879403328},
 {'Sunglasses': 1.884455990934764},
 {'Business Bags': 1.2539095659607755},
 {'Messenger Bags': 0.7869942695095339},
 {'Wristlets': 0.3168445902712999}]

In [41]:
df

,Category,Sub-Category,Sub-Sub-Category,Year,Month,Day,Week_Day,Rate of Change,Standard Dev,Popularity,Label
0,Bags and Travel,Men Bags,Backpacks,2023,1,14,Saturday,0.000000,174.916509,0,0.720472
1,Bags and Travel,Men Bags,Business Bags,2023,1,14,Saturday,0.000000,174.916509,0,0.469938
2,Bags and Travel,Men Bags,Crossbody Bags,2023,1,14,Saturday,0.000000,174.916509,0,0.896085
3,Bags and Travel,Men Bags,Messenger Bags,2023,1,14,Saturday,0.000000,174.916509,0,0.026298
4,Bags and Travel,Men Bags,Wallets & Accessories,2023,1,14,Saturday,0.000000,174.916509,0,0.559767
...,...,...,...,...,...,...,...,...,...,...,...
52483,Watches Sunglasses Jewellery,Jewellery,Men,2023,4,11,Tuesday,0.014599,277.523750,0,0.636126
52484,Watches Sunglasses Jewellery,Jewellery,Women,2023,4,11,Tuesday,0.000000,277.523750,0,0.444496
52485,Watches Sunglasses Jewellery,Watches,Kids,2023,4,11,Tuesday,-0.122302,277.523750,0,0.192020
52486,Watches Sunglasses Jewellery,Watches,Men,2023,4,11,Tuesday,-0.018957,277.523750,0,0.129965
52487,Watches Sunglasses Jewellery,Watches,Women,2023,4,11,Tuesday,-0.044643,277.523750,0,0.117935

In [58]:
grouped_df = df.groupby(['Year', 'Month', 'Day']).agg({'Rate of Change': 'mean'}).reset_index()
x = list(grouped_df[-30:]['Rate of Change'])
tremar = []
avg = 0
count = 0
for i in range(len(x)):
    avg += x[i]
    count += 1
    tremar.append({"name":i, 'market_trend':x[i], 'running_average': avg/count})

In [59]:
tremar

[{'name': 0,
  'market_trend': 0.8041041111998899,
  'running_average': 0.8041041111998899},
 {'name': 1,
  'market_trend': 0.12764196807478578,
  'running_average': 0.46587303963733784},
 {'name': 2,
  'market_trend': 0.14628309285836552,
  'running_average': 0.3593430573776804},
 {'name': 3,
  'market_trend': 2.221333275393315,
  'running_average': 0.824840611881589},
 {'name': 4,
  'market_trend': -0.05581732054535256,
  'running_average': 0.6487090253962007},
 {'name': 5,
  'market_trend': 0.1786359333248368,
  'running_average': 0.5703635100509733},
 {'name': 6,
  'market_trend': 0.4428579737324278,
  'running_average': 0.5521484334340382},
 {'name': 7,
  'market_trend': 0.287552946576823,
  'running_average': 0.5190739975768863},
 {'name': 8,
  'market_trend': 0.0964986642234884,
  'running_average': 0.4721211827598421},
 {'name': 9,
  'market_trend': 0.9438861745408892,
  'running_average': 0.5192976819379468},
 {'name': 10,
  'market_trend': 0.38961175735282205,
  'running_average': 0.5075080524302081},
 {'name': 11,
  'market_trend': 0.05428686549774257,
  'running_average': 0.469739620185836},
 {'name': 12,
  'market_trend': 0.03629069776707908,
  'running_average': 0.43639739538439315},
 {'name': 13,
  'market_trend': 0.016748112904340837,
  'running_average': 0.406422446635818},
 {'name': 14,
  'market_trend': -0.2929297203067018,
  'running_average': 0.35979896883965},
 {'name': 15,
  'market_trend': 4.530753103391849,
  'running_average': 0.6204836022491624},
 {'name': 16,
  'market_trend': 1.150535801618762,
  'running_average': 0.6516631433885507},
 {'name': 17,
  'market_trend': 0.03145693861780704,
  'running_average': 0.6172072431235094},
 {'name': 18,
  'market_trend': 0.014623805054004567,
  'running_average': 0.5854923253303775},
 {'name': 19,
  'market_trend': -0.36305262928499615,
  'running_average': 0.5380650775996089},
 {'name': 20,
  'market_trend': 5.347405712929566,
  'running_average': 0.7670812983296068},
 {'name': 21,
  'market_trend': 0.3467959489626345,
  'running_average': 0.7479774188129262},
 {'name': 22,
  'market_trend': 0.13133034697501314,
  'running_average': 0.7211666765591039},
 {'name': 23,
  'market_trend': -0.05934992452378572,
  'running_average': 0.6886451515139834},
 {'name': 24,
  'market_trend': 0.2730690301808592,
  'running_average': 0.6720221066606585},
 {'name': 25,
  'market_trend': 0.02293484608712728,
  'running_average': 0.6470572120232151},
 {'name': 26,
  'market_trend': 0.35118128166876134,
  'running_average': 0.6360988442323093},
 {'name': 27,
  'market_trend': 0.08605667287053158,
  'running_average': 0.6164544809693887},
 {'name': 28,
  'market_trend': 0.016325874429562636,
  'running_average': 0.595760391088705},
 {'name': 29,
  'market_trend': 0.023034209908618878,
  'running_average': 0.5766695183827022}]